import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../models/lead_model.dart';
import '../../providers/lead_provider.dart';

class AddLeadScreen extends ConsumerStatefulWidget { const AddLeadScreen({super.key}); @override ConsumerState<AddLeadScreen> createState() => _AddLeadScreenState(); }
class _AddLeadScreenState extends ConsumerState<AddLeadScreen> {
  final _form = GlobalKey<FormState>(); final _name = TextEditingController(); final _phone = TextEditingController(); final _site = TextEditingController();
  String _status = 'New'; String? _assignee; DateTime? _followUp; bool _loading = false; List<Map<String, dynamic>> _users = [];
  @override void initState() { super.initState(); _loadAssignees(); }
  Future<void> _loadAssignees() async { final rows = await Supabase.instance.client.from('profiles').select('id,full_name,email,role').order('full_name'); if (mounted) setState(() => _users = List<Map<String, dynamic>>.from(rows)); }
  @override void dispose() { _name.dispose(); _phone.dispose(); _site.dispose(); super.dispose(); }
  Future<void> _save() async { if (!_form.currentState!.validate()) return; setState(() => _loading = true); try { await ref.read(leadProvider.notifier).addLead(LeadModel(name: _name.text.trim(), phone: _phone.text.trim(), site: _site.text.trim(), status: _status, assignedTo: _assignee, followUpDate: _followUp)); if (mounted) Navigator.pop(context); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Could not save: $e'))); } if (mounted) setState(() => _loading = false); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Add lead')), body: Form(key: _form, child: ListView(padding: const EdgeInsets.all(20), children: [_field(_name, 'Customer name', validator: (v) => v!.trim().isEmpty ? 'Name is required' : null), const SizedBox(height: 14), _field(_phone, 'Phone number', type: TextInputType.phone, validator: (v) => v!.trim().isEmpty ? 'Phone is required' : null), const SizedBox(height: 14), _field(_site, 'Interested site', validator: (v) => v!.trim().isEmpty ? 'Site is required' : null), const SizedBox(height: 14), DropdownButtonFormField<String>(value: _status, decoration: const InputDecoration(labelText: 'Status'), items: const ['New','Follow-up','Qualified','Booked','Lost'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(), onChanged: (value) => setState(() => _status = value!)), const SizedBox(height: 14), DropdownButtonFormField<String>(value: _assignee, decoration: const InputDecoration(labelText: 'Assign to sales user'), hint: const Text('Choose employee'), items: _users.map((user) => DropdownMenuItem(value: user['id'] as String, child: Text((user['full_name'] as String?)?.isNotEmpty == true ? user['full_name'] as String : user['email'] as String))).toList(), onChanged: (value) => setState(() => _assignee = value)), const SizedBox(height: 14), OutlinedButton.icon(onPressed: () async { final date = await showDatePicker(context: context, firstDate: DateTime(2024), lastDate: DateTime(2100), initialDate: _followUp ?? DateTime.now()); if (date != null) setState(() => _followUp = date); }, icon: const Icon(Icons.calendar_today_outlined), label: Text(_followUp == null ? 'Set follow-up date' : _followUp!.toIso8601String().split('T').first)), const SizedBox(height: 24), FilledButton(onPressed: _loading ? null : _save, child: Text(_loading ? 'Saving…' : 'Save lead'))]));
  Widget _field(TextEditingController controller, String label, {TextInputType? type, String? Function(String?)? validator}) => TextFormField(controller: controller, keyboardType: type, validator: validator, decoration: InputDecoration(labelText: label));
}
