import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../models/lead_model.dart';
import '../../providers/lead_provider.dart';

class EditLeadScreen extends ConsumerStatefulWidget { const EditLeadScreen({super.key, required this.lead}); final LeadModel lead; @override ConsumerState<EditLeadScreen> createState() => _EditLeadScreenState(); }
class _EditLeadScreenState extends ConsumerState<EditLeadScreen> {
  final _form = GlobalKey<FormState>(); late final TextEditingController _name; late final TextEditingController _phone; late final TextEditingController _site; late String _status; String? _assignee; DateTime? _followUp; bool _saving = false; List<Map<String, dynamic>> _users = [];
  @override void initState() { super.initState(); _name = TextEditingController(text: widget.lead.name); _phone = TextEditingController(text: widget.lead.phone); _site = TextEditingController(text: widget.lead.site); _status = widget.lead.status; _assignee = widget.lead.assignedTo; _followUp = widget.lead.followUpDate; _loadUsers(); }
  Future<void> _loadUsers() async { final rows = await Supabase.instance.client.from('profiles').select('id,full_name,email').order('full_name'); if (mounted) setState(() => _users = List<Map<String, dynamic>>.from(rows)); }
  @override void dispose() { _name.dispose(); _phone.dispose(); _site.dispose(); super.dispose(); }
  Future<void> _save() async { if (!_form.currentState!.validate()) return; setState(() => _saving = true); try { await ref.read(leadProvider.notifier).updateLead(widget.lead.copyWith(name: _name.text.trim(), phone: _phone.text.trim(), site: _site.text.trim(), status: _status, assignedTo: _assignee, followUpDate: _followUp)); if (mounted) Navigator.pop(context); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Could not update: $e'))); } if (mounted) setState(() => _saving = false); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Edit lead')), body: Form(key: _form, child: ListView(padding: const EdgeInsets.all(20), children: [_input(_name, 'Customer name'), const SizedBox(height: 14), _input(_phone, 'Phone number', phone: true), const SizedBox(height: 14), _input(_site, 'Interested site'), const SizedBox(height: 14), DropdownButtonFormField<String>(value: _status, decoration: const InputDecoration(labelText: 'Status'), items: const ['New','Follow-up','Qualified','Booked','Lost'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(), onChanged: (v) => setState(() => _status = v!)), const SizedBox(height: 14), DropdownButtonFormField<String>(value: _assignee, decoration: const InputDecoration(labelText: 'Assigned sales user'), items: _users.map((u) => DropdownMenuItem(value: u['id'] as String, child: Text((u['full_name'] as String?)?.isNotEmpty == true ? u['full_name'] as String : u['email'] as String))).toList(), onChanged: (v) => setState(() => _assignee = v)), const SizedBox(height: 14), OutlinedButton.icon(onPressed: () async { final date = await showDatePicker(context: context, initialDate: _followUp ?? DateTime.now(), firstDate: DateTime(2024), lastDate: DateTime(2100)); if (date != null) setState(() => _followUp = date); }, icon: const Icon(Icons.calendar_today_outlined), label: Text(_followUp == null ? 'Set follow-up date' : _followUp!.toIso8601String().split('T').first)), const SizedBox(height: 24), FilledButton(onPressed: _saving ? null : _save, child: Text(_saving ? 'Updating…' : 'Update lead'))]));
  Widget _input(TextEditingController c, String label, {bool phone = false}) => TextFormField(controller: c, keyboardType: phone ? TextInputType.phone : null, validator: (v) => v!.trim().isEmpty ? '$label is required' : null, decoration: InputDecoration(labelText: label));
}
